name: Simulation

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  ROM_alone_sim:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - name: 'Run ROM ALONE sim'
        uses: docker://docker.io/ghdl/vunit:mcode-master
        with:
          args: ./sim/MEM/ROM/job_ROM_alone_sim.sh

      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ROM_ALONE_SIM_FILES
          path: |
            ./wave_ROM_all_8.vcd
            ./wave_ROM_all_16.vcd
            ./wave_ROM_all_32.vcd
            ./wave_ROM_partial_8.vcd
            ./wave_ROM_partial_16.vcd
            ./wave_ROM_partial_32.vcd
            ./tb_ROM_all_8.csv
            ./tb_ROM_all_16.csv
            ./tb_ROM_all_32.csv
            ./tb_ROM_partial_8.csv
            ./tb_ROM_partial_16.csv
            ./tb_ROM_partial_32.csv

  ROM_wishbone_alone_sim:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - name: 'Run ROM wishbone ALONE sim'
        uses: docker://docker.io/ghdl/vunit:mcode-master
        with:
          args: ./sim/MEM/ROM/wishbone/job_ROM_wishbone_alone_sim.sh

      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ROM_wishbone_ALONE_SIM_FILES
          path: |
            ./wave_ROM_wishbone_all_8.vcd
            ./wave_ROM_wishbone_all_16.vcd
            ./wave_ROM_wishbone_all_32.vcd
            ./wave_ROM_wishbone_partial_8.vcd
            ./wave_ROM_wishbone_partial_16.vcd
            ./wave_ROM_wishbone_partial_32.vcd
            ./tb_ROM_wishbone_all_8.csv
            ./tb_ROM_wishbone_all_16.csv
            ./tb_ROM_wishbone_all_32.csv
            ./tb_ROM_wishbone_partial_8.csv
            ./tb_ROM_wishbone_partial_16.csv
            ./tb_ROM_wishbone_partial_32.csv

  neorv32_ROM_wishbone_alone_sim:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: 'Build software and run the simulations'
        run: |
          podman pull ghcr.io/stnolting/neorv32/sim:latest
          podman run --rm -tv $(pwd):/wrk:Z -w /wrk stnolting/neorv32/sim:latest ./sim/MEM/ROM/neorv32/job_neorv32_ROM_wishbone_alone_sim-build.sh
          podman pull docker.io/ghdl/vunit:mcode-master
          podman run --rm -tv $(pwd):/wrk:Z -w /wrk ghdl/vunit:mcode-master ./sim/MEM/ROM/neorv32/job_neorv32_ROM_wishbone_alone_sim-run.sh

      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: neorv32_ROM_wishbone_ALONE_SIM_FILES
          path: |
            ./wave_neorv32_ROM_wishbone_partial_8.vcd
            ./wave_neorv32_ROM_wishbone_partial_16.vcd
            ./wave_neorv32_ROM_wishbone_partial_32.vcd
            ./wave_neorv32_ROM_wishbone_all_8.vcd
            ./tb_neorv32_ROM_wishbone_partial_8.csv
            ./tb_neorv32_ROM_wishbone_partial_16.csv
            ./tb_neorv32_ROM_wishbone_partial_32.csv
            ./tb_neorv32_ROM_wishbone_all_8.csv
            ./tb_neorv32_ROM_wishbone_all_16.csv
            ./tb_neorv32_ROM_wishbone_all_32.csv

  RAM_alone_sim:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - name: 'Run RAM ALONE sim'
        uses: docker://docker.io/ghdl/vunit:mcode-master
        with:
          args: ./sim/MEM/RAM/job_RAM_alone_sim.sh

      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: RAM_ALONE_SIM_FILES
          path: |
            ./wave_RAM_8.vcd
            ./wave_RAM_16.vcd
            ./wave_RAM_32.vcd
            ./tb_RAM_8.csv
            ./tb_RAM_16.csv
            ./tb_RAM_32.csv
            ./8_string.hex
            ./16_string.hex
            ./32_string.hex

  RAM_wishbone_alone_sim:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - name: 'Run RAM wishbone ALONE sim'
        uses: docker://docker.io/ghdl/vunit:mcode-master
        with:
          args: ./sim/MEM/RAM/wishbone/job_RAM_wishbone_alone_sim.sh

      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: RAM_wishbone_ALONE_SIM_FILES
          path: |
            ./wave_RAM_wishbone_8.vcd
            ./wave_RAM_wishbone_16.vcd
            ./wave_RAM_wishbone_32.vcd
            ./tb_RAM_wishbone_8.csv
            ./tb_RAM_wishbone_16.csv
            ./tb_RAM_wishbone_32.csv
            ./8_string.hex
            ./16_string.hex
            ./32_string.hex

  neorv32_RAM_wishbone_alone_sim:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: 'Build software and run the simulations'
        run: |
          podman pull ghcr.io/stnolting/neorv32/sim:latest
          podman run --rm -tv $(pwd):/wrk:Z -w /wrk stnolting/neorv32/sim:latest ./sim/MEM/RAM/neorv32/job_neorv32_RAM_wishbone_alone_sim-build.sh
          podman pull docker.io/ghdl/vunit:mcode-master
          podman run --rm -tv $(pwd):/wrk:Z -w /wrk ghdl/vunit:mcode-master ./sim/MEM/RAM/neorv32/job_neorv32_RAM_wishbone_alone_sim-run.sh

      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: neorv32_RAM_wishbone_ALONE_SIM_FILES
          path: |
            ./wave_neorv32_RAM_wishbone_8.vcd
            ./wave_neorv32_RAM_wishbone_16.vcd
            ./wave_neorv32_RAM_wishbone_32.vcd
            ./tb_neorv32_RAM_wishbone_8.csv
            ./tb_neorv32_RAM_wishbone_16.csv
            ./tb_neorv32_RAM_wishbone_32.csv
            ./8_string.hex
            ./16_string.hex
            ./32_string.hex
